export default{
    getMpmeData: (state) => state.mpmeData,
    getmpme: (state) => state.mpmeAll,
    getRegionOptions: (state) => state.regionOptions,
    getRegionOptions2: (state) => state.regionOptions2,
    getCountryOptions: (state) => state.countryOptions,
    getprefectureOptions : (state) => state.prefectureOptions,
    getSousprefectureOptions : (state) => state.SousprefectureOptions,
    getQuartierOptions : (state) => state.QuartierOptions,
    getsecteurActiviteOptions: (state) => state.secteurActiviteOptions,
    getsecteurActiviteOptions2: (state) => state.secteurActiviteOptions2,
    getSousSecteurOptions: (state) => state.sousSecteurOptions,
    getStatutJuridiqueOptions: (state) => state.statutJuridiqueOptions,
    getBourseOptions: (state) => state.bourseOptions,
    loggedInMPME: (state) => state.loggedInMPME,
    getSousDocOptions: (state) => state.sousdocOptions,
    getSousCategoriesData: (state) => state.sousCategoriesData,
    getCategoriesData: (state) => state.categoriesData,
    getPubliqueData: (state) => state.publiqueData,
    getTotalEmploisFemme: (state) => state.totalEmploisFemme,
    getTotalMpme: (state) => state.totalMpme,
    getTypeCartesData: (state) => state.typeCartesData,
    getTypeComptabilitesData: (state) => state.typeComptabilitesData,
    getTypeDemandesData: (state) => state.typeDemandesData,
    getActualites:(state) => state.actualites,
    getPartenaires:(state)  => state.partenaires,
    getRegimes: (state) => state.regimes,
    getTypesGestions: (state) => state.typesGestions,
    getTypesContribuables: (state) => state.typesContribuables,
    getPubliqueVisiblePhotos: (state) => state.publiqueVisiblePhotos,

    getSousSecteursOptions: (state) =>state.sousSecteurs,
    getAccompagnementData: (state) => state.accompagnementData,
    getPersonnelData: (state) => state.personnelData,
    getdirections: (state) => state.directions,
      


}