export default{
    mpmeData: [],
    getmpme:[],
    regionOptions: [],
    regionOptions2: [],
    countryOptions: [],
    prefectureOptions: [],
    SousprefectureOptions:[],
    QuartierOptions:[],
    secteurActiviteOptions: [],
    secteurActiviteOptions2: [],
    sousSecteurOptions: [],
    statutJuridiqueOptions: [],
    bourseOptions: [],
    loggedInMPME: null,
    sousdocOptions:[],
    sousCategoriesData: [],   
    categoriesData: [],
    publiqueData: [],
    totalEmploisFemme: 0,
    totalMpme: 0,
    typeCartesData: [], 
    typeComptabilitesData: [], 
    typeDemandesData:[],
    actualites: [],
    partenaires: [],
    regimes: [],
    typesGestions: [],
    typesContribuables: [],
    publiqueVisiblePhotos: [],
    sousSecteurs: [],
    accompagnementData: [],
    personnelData: [],
    directions: []

}